<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="23516" started-at="2015-04-17T17:51:58Z" finished-at="2015-04-17T17:52:22Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="23516" started-at="2015-04-17T17:51:58Z" finished-at="2015-04-17T17:52:22Z">
      <class name="pageObjects.test.TestCasesByTestNG">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:pageObjects.test.TestCasesByTestNG@17bd6a1]" name="openBrowser" is-config="true" duration-ms="18959" started-at="2015-04-17T23:21:58Z" finished-at="2015-04-17T23:22:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="FAIL" signature="test_Home_page()[pri:0, instance:pageObjects.test.TestCasesByTestNG@17bd6a1]" name="test_Home_page" duration-ms="4557" started-at="2015-04-17T23:22:17Z" finished-at="2015-04-17T23:22:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Password:> but was:<Password1:>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Password:> but was:<Password1:>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at pageObjects.test.TestCasesByTestNG.test_Home_page(TestCasesByTestNG.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_Home_page -->
      </class> <!-- pageObjects.test.TestCasesByTestNG -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
